### ISSUE TITLE
MQTT credential

### ISSUE THREAD

**Issue by BeardedTinker** [HutchieV/ESP8266-MQTT-Thermal-Printer#1]
Is there a way to define username/password for MQTT server connection?

**Comment by BCJMilne** [comment]
Unforunately not at present

**Comment by BeardedTinker** [comment]
I think I've found a way of using mqtt-auth from PubSubClient 
Created for and if I manage to test it I'll make pull request.

**Comment by BCJMilne** [comment]
> 
> 
> I think I've found a way of using mqtt-auth from PubSubClient
> Created for and if I manage to test it I'll make pull request.

Awesome! I haven't looked at this in a while - would be interesting to expand on it

**Comment by BeardedTinker** [comment]
#2 made pull request.
I didn't test printing part as I still haven't connected everything together, but MQTT connection works.
Thanks for the project! This was exactly what I was looking for one of my projects.

**Comment by BeardedTinker** [comment]
Just to add on this - tested it with sending text via MQTT and it works perfectly. Prints really good.

**Comment by HutchieV** [comment]
Thank you for sharing the time and effort to build upon the project!
